export const personalInfo = {
  name: "Adam Elmekadem",
  title: "Junior Full Stack Developer",
  subtitle: "Web development, digital design, and intuitive interfaces",
  bio: "I am Adam Elmekadem, 23 years old, a digital developer and graphic designer. I build web projects that combine creativity and functionality, with a strong drive to innovate.",
  location: "Sidi Moussa, Sale",
  email: "adamelmekadem1@gmail.com",
  github: "https://github.com/Adam-Elmekadem",
  linkedin: "https://linkedin.com/in/adam-elmekadem",
  twitter: "https://github.com/Adam-Elmekadem",
};

export const projects = [
  {
    id: 1,
    title: "A&K Store",
    description: "Front-end e-commerce application designed for clear navigation, clean visuals, and a fast mobile experience.",
    tags: ["React JS", "Front End", "UI"],
    color: "#22d3ee",
    gradient: "from-cyan-500 to-indigo-600",
    year: "2024",
    link: "#",
    github: "#",
  },
  {
    id: 2,
    title: "Certif-Ease",
    description: "Certificate management platform with a simple interface for editing, tracking, and reviewing documents.",
    tags: ["Laravel", "HTML", "CSS", "JS"],
    color: "#a855f7",
    gradient: "from-purple-500 to-pink-600",
    year: "2024",
    link: "#",
    github: "#",
  },
  {
    id: 3,
    title: "Landing Page Studio",
    description: "Lightweight, structured landing pages to present a service or brand with clear visual hierarchy.",
    tags: ["HTML5", "CSS3", "Responsive", "SEO"],
    color: "#6366f1",
    gradient: "from-indigo-500 to-cyan-600",
    year: "2023",
    link: "#",
    github: "#",
  },
  {
    id: 4,
    title: "Dashboard Admin",
    description: "Admin interface built to monitor content, users, and key actions at a glance.",
    tags: ["React", "PHP", "MySQL", "UI"],
    color: "#ec4899",
    gradient: "from-pink-500 to-purple-600",
    year: "2023",
    link: "#",
    github: "#",
  },
  {
    id: 5,
    title: "Portfolio Web",
    description: "Personal website focused on content clarity, readability, and visual identity.",
    tags: ["Next.js", "Design", "Motion"],
    color: "#f59e0b",
    gradient: "from-amber-500 to-orange-600",
    year: "2022",
    link: "#",
    github: "#",
  },
  {
    id: 6,
    title: "Brand Identity Pack",
    description: "Visual explorations for logo, business card, and social graphics within a consistent brand system.",
    tags: ["Figma", "Branding", "Graphics"],
    color: "#10b981",
    gradient: "from-emerald-500 to-cyan-600",
    year: "2022",
    link: "#",
    github: "#",
  },
];

export const skills = [
  { name: "HTML5 / CSS3", level: 95, category: "Frontend", icon: "⚛" },
  { name: "JavaScript", level: 92, category: "Language", icon: "JS" },
  { name: "React", level: 88, category: "Frontend", icon: "⬢" },
  { name: "PHP / Laravel", level: 84, category: "Backend", icon: "◈" },
  { name: "TailwindCSS", level: 86, category: "UI", icon: "✦" },
  { name: "Bootstrap", level: 80, category: "UI", icon: "🐘" },
  { name: "Figma", level: 90, category: "Design", icon: "🎨" },
  { name: "Python", level: 70, category: "Tools", icon: "🐍" },
];

export const techStack = [
  "HTML5", "CSS3", "JavaScript", "React", "PHP", "Laravel",
  "TailwindCSS", "Bootstrap", "Python", "Figma", "Git", "MySQL",
  "Next.js", "Node.js", "GSAP", "Framer Motion", "Vercel", "SEO",
];

export const experience = [
  {
    role: "SNRT Internship",
    company: "SNRT",
    period: "1 month / Sale, Morocco",
    description: "Developed a Laravel application under the supervision of the head of the building and television archive service.",
    achievements: ["Video archive management", "Admin interface", "Team collaboration"],
    color: "#22d3ee",
  },
  {
    role: "Graphic Designer Freelance",
    company: "Upwork & Fiverr",
    period: "2022 — 2024 / Sale, Morocco",
    description: "Graphic design experience for international clients, including visual identity development, creative project management, and team collaboration.",
    achievements: ["Visual identities", "Creative projects", "International collaboration"],
    color: "#a855f7",
  },
  {
    role: "Digital Project",
    company: "Studies and personal practice",
    period: "2020 — 2022",
    description: "Designed personal web projects focused on front-end development, interface design, and content structure.",
    achievements: ["Clean front-end", "UI experimentation", "Continuous learning"],
    color: "#6366f1",
  },
  {
    role: "Continuous Learning",
    company: "Web and digital design",
    period: "2018 — 2020",
    description: "Learned web development fundamentals, graphic design, and the tools needed to build clean, effective interfaces.",
    achievements: ["Web fundamentals", "Design software", "Self-reliance"],
    color: "#ec4899",
  },
];
