export const personalInfo = {
  name: "Adam Elmekadem",
  title: "Développeur Full Stack Jr",
  subtitle: "Développement web, design digital et interfaces intuitives",
  bio: "Je suis Adam Elmekadem, j'ai 23 ans, développeur digital et designer graphique. Je crée des projets web alliant créativité et fonctionnalité, avec une forte volonté d'innover.",
  location: "Sidi Moussa, Salé",
  email: "adamelmekadem1@gmail.com",
  github: "https://github.com/Adam-Elmekadem",
  linkedin: "https://linkedin.com/in/adam-elmekadem",
  twitter: "https://github.com/Adam-Elmekadem",
};

export const projects = [
  {
    id: 1,
    title: "A&K Store",
    description: "Application e-commerce front-end pensée pour une navigation claire, des visuels propres et une expérience rapide sur mobile.",
    tags: ["React JS", "Front End", "UI"],
    color: "#22d3ee",
    gradient: "from-cyan-500 to-indigo-600",
    year: "2024",
    link: "#",
    github: "#",
  },
  {
    id: 2,
    title: "Certif-Ease",
    description: "Plateforme de gestion de certificats avec une interface simple pour l'édition, le suivi et la consultation des documents.",
    tags: ["Laravel", "HTML", "CSS", "JS"],
    color: "#a855f7",
    gradient: "from-purple-500 to-pink-600",
    year: "2024",
    link: "#",
    github: "#",
  },
  {
    id: 3,
    title: "Landing Page Studio",
    description: "Pages vitrines légères et structurées pour présenter un service ou une marque avec une hiérarchie claire.",
    tags: ["HTML5", "CSS3", "Responsive", "SEO"],
    color: "#6366f1",
    gradient: "from-indigo-500 to-cyan-600",
    year: "2023",
    link: "#",
    github: "#",
  },
  {
    id: 4,
    title: "Dashboard Admin",
    description: "Interface d'administration conçue pour suivre des contenus, des utilisateurs et des actions principales en un coup d'œil.",
    tags: ["React", "PHP", "MySQL", "UI"],
    color: "#ec4899",
    gradient: "from-pink-500 to-purple-600",
    year: "2023",
    link: "#",
    github: "#",
  },
  {
    id: 5,
    title: "Portfolio Web",
    description: "Site personnel centré sur la clarté du contenu, la lisibilité et l'identité visuelle.",
    tags: ["Next.js", "Design", "Motion"],
    color: "#f59e0b",
    gradient: "from-amber-500 to-orange-600",
    year: "2022",
    link: "#",
    github: "#",
  },
  {
    id: 6,
    title: "Brand Identity Pack",
    description: "Explorations visuelles pour logo, carte de visite et visuels sociaux dans une logique cohérente de marque.",
    tags: ["Figma", "Branding", "Graphics"],
    color: "#10b981",
    gradient: "from-emerald-500 to-cyan-600",
    year: "2022",
    link: "#",
    github: "#",
  },
];

export const skills = [
  { name: "HTML5 / CSS3", level: 95, category: "Frontend", icon: "⚛" },
  { name: "JavaScript", level: 92, category: "Language", icon: "JS" },
  { name: "React", level: 88, category: "Frontend", icon: "⬢" },
  { name: "PHP / Laravel", level: 84, category: "Backend", icon: "◈" },
  { name: "TailwindCSS", level: 86, category: "UI", icon: "✦" },
  { name: "Bootstrap", level: 80, category: "UI", icon: "🐘" },
  { name: "Figma", level: 90, category: "Design", icon: "🎨" },
  { name: "Python", level: 70, category: "Tools", icon: "🐍" },
];

export const techStack = [
  "HTML5", "CSS3", "JavaScript", "React", "PHP", "Laravel",
  "TailwindCSS", "Bootstrap", "Python", "Figma", "Git", "MySQL",
  "Next.js", "Node.js", "GSAP", "Framer Motion", "Vercel", "SEO",
];

export const experience = [
  {
    role: "Stage SNRT",
    company: "SNRT",
    period: "1 mois / Salé, Maroc",
    description: "Développement d'une application Laravel sous la supervision du responsable du service des archives du bâtiment et de la télévision.",
    achievements: ["Gestion des archives vidéo", "Interface d'administration", "Travail en équipe"],
    color: "#22d3ee",
  },
  {
    role: "Graphic Designer Freelance",
    company: "Upwork & Fiverr",
    period: "2022 — 2024 / Salé, Maroc",
    description: "Expérience en design graphique pour des clients internationaux, développement d'identités visuelles, gestion de projets créatifs et collaboration en équipe.",
    achievements: ["Identités visuelles", "Projets créatifs", "Collaboration internationale"],
    color: "#a855f7",
  },
  {
    role: "Projet Digital",
    company: "Études et pratique personnelle",
    period: "2020 — 2022",
    description: "Conception de projets web personnels avec focus sur le front-end, l'interface et la structuration de contenu.",
    achievements: ["Front-end propre", "Expérimentation UI", "Apprentissage continu"],
    color: "#6366f1",
  },
  {
    role: "Formation continue",
    company: "Web et design digital",
    period: "2018 — 2020",
    description: "Apprentissage des bases du développement web, du graphisme et des outils nécessaires pour construire des interfaces propres et efficaces.",
    achievements: ["Bases web", "Logiciels de design", "Autonomie"],
    color: "#ec4899",
  },
];
